name: Python Tests

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"] # Using Python 3.9 as per runtime.txt

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] # Installs package and dev dependencies from setup.py

      - name: Run tests
        run: |
          export PYTHONPATH=. # Set PYTHONPATH to current directory
          python -m unittest discover -s src/tests -p 'test_*.py'
